### ISSUE TITLE
Source code for the GRAFF

### ISSUE THREAD

**Issue by Colin-KelinLi** [priyankamandikal/graff#2]
Hi Priyanka,

Your GRAFF work is brilliant and inspired me a lot. Is it possible to find the source code for the GRAFF framework somewhere? Thank you very much!

**Comment by priyankamandikal** [comment]
Hi Colin,

Thanks for your interest in this work. I will push the code to this repository in a couple of days.

**Comment by Colin-KelinLi** [comment]
Thanks for your reply @priyankamandikal 

I just tried to reproduce the code shown in Fig.4 of your paper. 
![IMG_6158](https://github.com/priyankamandikal/graff/assets/24929885/6956bb42-334e-43fe-8ca6-4dfc51a1f6ce)

But I can’t get ideal results. I guess it is because I missed some details for the grasp policy architecture. As I am now running a project that may implement this it, would you mind just share this part of code with me earlier than you push the whole GRAFF repository? That would be a great help for me.  Many thanks!

**Comment by priyankamandikal** [comment]
Hi @Colin-KelinLi 

The full code is now available. For model implementation, please check:
https://github.com/priyankamandikal/graff/blob/main/a2c_ppo_acktr/model.py
