### ISSUE TITLE
json file in the contacts directory

### ISSUE THREAD

**Issue by binbinbai** [priyankamandikal/graff#4]
Hi,thank you for the great work!!!
For a new object, how to get the json file in the contacts directory

**Comment by priyankamandikal** [comment]
Hello,

For new objects, you need to train the 2D affordance prediction model on ContactDB. The code for training the model is here: https://github.com/priyankamandikal/graff/tree/main/affordance-pred

For inference on a new object, you can back-project the predicted 2D contact points to 3D using the depth map and save it in the json file.

**Comment by binbinbai** [comment]
Hello,thank for your answer. we want to do a comparative experiment with GRAFF. Can you provide the mesh and json files of unseen objects on the 3DNet dataset? Or the code using the depth map to get the json file from 2D contact points?      We are in a hurry to submit our paper, and time is extremely tight. If you can help us, we would be very grateful! @priyankamandikal

**Comment by priyankamandikal** [comment]
I've added supplementary code to evaluate on 3dnet and added some samples from a few categories. You can find the resources in the [3dnet branch](https://github.com/priyankamandikal/graff/tree/3dnet). Note that this is only a sample subset. To evaluate on more meshes, please train the affordance prediction model and process the outputs accordinly.

**Comment by binbinbai** [comment]
Thank you so much!!!!!!!!!!!! @priyankamandikal
