### ISSUE TITLE
How to render contact data without an adroit hand?

### ISSUE THREAD

**Issue by Charlie0257** [priyankamandikal/graff#6]
Hi, @priyankamandikal 
Thanks for your great work!

When I try the `python affordance-pred/render_contactdb_data.py`, there is always an adroit hand in the image.
How can I render the effect like you shown in the paper?
How to render contact data without an adroit hand?

Thanks for any help!
Best,
Charlie

**Comment by priyankamandikal** [comment]
Hi,

I believe there might be a way to make the hand invisible in mujoco by changing certain variables. Else, you can just [comment out these lines](https://github.com/priyankamandikal/graff/blob/main/envs/mj_envs/dex_manip/assets/contactdb/env_xmls/apple_vhacd.xml#L34-L51) in each obj xml to render only the object.

**Comment by Charlie0257** [comment]
Thanks for your help!
